#!/bin/bash
#find the nextion Nextion size
# early days reliese on at least one good loaf of NextionDriver in the syslog
CONFDIR=/home/pi-star/configs
DATADIR=/usr/local/etc
NEXTDIR=/home/pi-star/Pi-Star_switcher/Nextion/
VERSION="1.0.0 31May20"
version () {
  msg="Version: $(basename $0) $VERSION"
  returnmsg
  exit 0
}
MODX=`grep 'display model N' /var/log/syslog`
echo ${MODX##* }
