#!/bin/bash
#Routine to upload Nextion screen
#
# Quick version may get tidyer later
#
# DO NOT RUN via Nextion .. the stop of mmdvmhost will stop NExtionDriver killing the job
#

HOMEDIR=/home/pi-star
CONFDIR=/home/pi-star/configs
GITHOME=$HOMEDIR/Pi-Star_switcher
PISTUPDATE=/usr/local/sbin/pistar-update
VERSION="0.1.1rc1 5Dec18"
version () {
 msg="Version: $(basename $0) $VERSION"
 returnmsg
 exit 0
}
returnmsg () {
  echo $msg
}

usage () {
 echo "Usage: $(basename $0) "
 echo ""
 echo "      -h  This help text"
 echo "      -v  version"
 echo ""
 echo "initiates a backgrounded update of the Nextion"
}

test -r $CONFDIR || exit 1

overwrite=
# for future state with multiple options
while getopts "hv" opt ; do
  case $opt in

    h ) usage ;;
    v ) version ;;
#    O ) overwrite=1 ;;
   \? ) echo -e "Invalid option, try -h \"for help\"" ; exit 0 ;;
  esac
done
shift $(($OPTIND -1))
#  $* is left over
sudo mount -o remount,rw /
sleep 2
loadNextiond > $CONFDIR/loadNextion.log 2>&1 &
disown
