#!/bin/bash
#Routine to get status of the git
#
# Quick version may get tidyer later
#
# DO NOT RUN via Nextion .. the stop of mmdvmhost will stop NExtionDriver killing the job
#

HOMEDIR=/home/pi-star
CONFDIR=/home/pi-star/configs
GITHOME=$HOMEDIR/Pi-Star_switcher
PISTUPDATE=/usr/local/sbin/pistar-update
VERSION="0.1.1rc2 19Nov18"
version () {
 msg="Version: $(basename $0) $VERSION"
 returnmsg
 exit 0
}
returnmsg () {
  echo $msg
}

usage () {
 echo "Usage: $(basename $0) [-O]"
 echo ""
 echo "      -h  This help text"
 echo "      -v  version"
 echo ""
 echo "initiates a backgrounded update of the switcher software from git"
}


statusgit() {
 cd $GITHOME
 git remote update &> /dev/null
 UPSTREAM=${1:-'@{u}'}
 LOCAL=$(git rev-parse @)
 REMOTE=$(git rev-parse "$UPSTREAM")
 BASE=$(git merge-base @ "$UPSTREAM")


 if [ $LOCAL = $REMOTE ]; then
    echo "Current"
 elif [ $LOCAL = $BASE ]; then
    echo "Pull"
 elif [ $REMOTE = $BASE ]; then
    echo "Push"
 else
    echo "Diverged"
 fi
}

test -r $GITHOME || exit 1
test -r $PISTUPDATE || exit 1
while getopts "hv" opt ; do
  case $opt in
    h ) usage ;;
    v ) version ;;
   \? ) echo -e "Invalid option, try -h \"for help\"" ; exit 0 ;;
  esac
done
shift $(($OPTIND -1))
statusgit
