#!/bin/bash
#Routine to check or relink a config file

CONFDIR=/home/pi-star/configs
VERSION="0.9.7rc3 14Nov18"
version () {
 msg="Version: $(basename $0) $VERSION"
 returnmsg
 exit 0
}
returnmsg () {
  echo $msg
}
createdir () {
 if [ ! -d $CONFDIR ] ; then
  sleep 1
  sudo mount -o remount,rw /
  mkdir $CONFDIR
  sleep 1
  sudo mount -o remount,ro /
fi
}
findprof () {
  local __proftest=$1
  local proffind=`find $CONFDIR -name m*$1*| xargs -n 1 basename |cut -c2-`
# handle missing file condition here
  echo $proffind
}
findcurrent () {
mcurr="None"
for f in `find $CONFDIR/ -name m*$1*` ; do  if cmp -s /etc/mmdvmhost $f; then  mcurr=`basename $f|cut -c2-`; fi ; done
#mcurr=`readlink /etc/mmdvmhost | xargs -n 1 basename`
}

usage () {
 echo "Usage: $(basename $0) [ -i|-l|-s profile|-X profile [-O]]"
 echo ""
 echo "      -i  return current matched profile"
 echo "      -h  This help text"
 echo "      -l  return current list of profiles"
 echo "      -s profile  replace mmdvmhost"
 echo "      -t   as yet unspecified test"
 echo "      -v   version"
 echo "      -X profile   copy current mmdvmhost etc to configs/profile"
 echo "      -O  option to -X to confirm overwrite"
 echo ""
 echo "   profile stored as Xn-YYYY"
 echo "       X - internal value based on config ie m - mmdvmhost d - dstargateway y - ysfgateway ..."
 echo "       n - user supplied profile number e.g. 0"
 echo "       YYYY - user supplied short name"
 echo " TIDY UP syntax of X and s ie   X needs  0-ipsc to create m0-ipsc s just needs 0 or ipsc"

 echo "      profile field will search for  n or YYYY or n-YYYY"
 echo "files stored as '$CONFDIR'/m0-xxxx"
 echo ""
 echo "Example: $(basename $0) -X 3-bmes"
 echo "Will copy current mmdvmhost, dmrgateway, ...  into configs folder as m3-dmrg, d3-dmrg"
 echo " If this profile already exists use append -O to confirm overwriting"
 echo ""
 echo " $(basename $0) -s 0 or"
 echo " $(basename $0) -s ipsc or"
 echo " $(basename $0) -s 0-ipsc"
 echo "Will copy profile m0-ipsc, d0-ipsc to  mmdvmhost, dmrgateway, ... and restart"

 exit 0
}

#starting
mand=
if [ "$1" != "" ]; then
 overwrite=
 outinfo=
 outlist=
 oswitch=
 outtest=
 ocreate=


 # for future state with multiple options
 while getopts "ihlOs:tvX:" opt ; do
   case $opt in

     i ) outinfo=0 ;;
     h ) usage ;;
     l ) outlist=0 ;;
     s ) proftest="$OPTARG" ; oswitch=0 ;;
     l ) outlist=0 ;;
     t ) outtest=0 ;;
     v ) version ;;
     X ) profile="$OPTARG" ; ocreate=0 ;;
     O ) overwrite=1 ;;
    \? ) echo -e "Invalid option, try -h \"for help\"" ; exit 0 ;;
   esac
 done
 shift $(($OPTIND -1))
 #  $* is left over
 if [ -n "$ocreate" ] ; then
 # this did more when i tried linking leaving here for better initial state testing later
   ignorecurrent=1
 else
   findcurrent
 fi
else
 usage
fi

if [  -n "$outinfo" ]; then
  msg=$mcurr
  returnmsg
  exit 0
fi

if [  -n "$outlist" ]; then
  # expand later to handle ircddbgateway rather than mmdvmhost
  msg=`find $CONFDIR/* -name m*$1*| xargs -n 1 basename |cut -c2- | sort | xargs`
  returnmsg
  exit 0
fi

if [  -n "$oswitch" ]; then
  msg="switching"
  profile=$(findprof $proftest)
  if [ -z $profile ]; then profile="None" ; fi
  msg="$msg $profile"
 if [ ! -f $CONFDIR/$profile/m$profile ]; then
   msg="$msg profile: $profile not found"
   returnmsg
   exit 0
 else
   mnext=`basename $CONFDIR/$profile/m$profile`
 fi
 if [ $mnext = "m$mcurr" ]; then
   msg="$msg same as current profile $mcurr:$mnext "
   returnmsg
   exit 0
 fi
 # this is probably still not the best to handle potential overlap of restarts
 # wait for these to stop or the restore will fail if busy
 returnmsg
 sleep 2
 sudo mount -o remount,rw /
 sudo tar -xPzf $CONFDIR/$profile/$profile.tgz
 sleep 1
 swstopstart restart
# as soon as mmdvmhost restarts the Nextion will disconnect
#let cron take care of the ro
# sudo mount -o remount,ro /

fi

if [  -n "$ocreate" ]; then
  createdir
  if [  -f $CONFDIR/$profile/m$profile ] && [ "$overwrite" != "1" ] ; then
    msg="profile: $mprofile exists specify overwrite -O"
    returnmsg
    exit 1
  else
   sleep 1
# arbitrary collection of configs
   sudo mount -o remount,rw /
   if [ ! -d $CONFDIR/$profile ] ; then
    mkdir $CONFDIR/$profile
  fi
   cp /etc/mmdvmhost  $CONFDIR/$profile/m$profile
   tar -czPT $CONFDIR/MMDVM.conflist -f $CONFDIR/$profile/$profile.tgz

   sleep 1
   sudo mount -o remount,ro /
  fi
fi
