#!/bin/bash
#Routine to stop or start services
#
# Quick version may get tidyer later
#
# DO NOT RUN directly via Nextion .. the stop of mmdvmhost will stop NExtionDriver killing the job
#
PISTUPDATE=/usr/local/sbin/pistar-update
VERSION="0.1.0rc1 14Nov18"
version () {
 msg="Version: $(basename $0) $VERSION"
 returnmsg
 exit 0
}
returnmsg () {
  echo $msg
}

usage () {
 echo "Usage: $(basename $0) [stop|start]"
 echo ""
 echo "      stop  stop pistar mmdvm services"
 echo "      start start pistar services"
 echo "      restart   converts start to restart of pistar services"
 echo ""
}

test -r $PISTUPDATE || exit 1

sudo mount -o remount,rw /
sudo echo 'dowhat=${1}' >/tmp/pistarservices
sudo grep 'systemctl ' $PISTUPDATE >>/tmp/pistarservices

case $1 in

  stop)
    sudo sh /tmp/pistarservices stop &
    exit 0
    ;;

  start)
    sudo sh /tmp/pistarservices start &
    exit 0
    ;;

  restart)
    sudo sh /tmp/pistarservices restart &
    exit 0
    ;;


  *)
    usage
    exit 1
esac

# cron can take care of the readonly
