#!/bin/bash
#Routine to update switcher
#
# Quick version may get tidyer later
#
# DO NOT RUN via Nextion .. the stop of mmdvmhost will stop NExtionDriver killing the job
#
PREFIX=/usr/local/sbin
HOMEDIR=/home/pi-star
CONFDIR=/home/pi-star/configs
GITHOME=$HOMEDIR/Pi-Star_switcher
PISTUPDATE=/usr/local/sbin/pistar-update
VERSION="1.0 30Aug19"
version () {
 msg="Version: $(basename $0) $VERSION"
 returnmsg
 exit 0
}
returnmsg () {
  echo $msg
}

usage () {
 echo "Usage: $(basename $0) [-O]"
 echo ""
 echo "      -O  Confirm run update"
 echo "      -h  This help text"
 echo "      -v  version"
 echo ""
 echo "initiates a backgrounded update of the switcher software from git"
}

test -r $GITHOME || exit 1
test -r $PISTUPDATE || exit 1

overwrite=
# for future state with multiple options
while getopts "hOv" opt ; do
  case $opt in

    h ) usage ;;
    v ) version ;;
    O ) overwrite=1 ;;
   \? ) echo -e "Invalid option, try -h \"for help\"" ; exit 0 ;;
  esac
done
shift $(($OPTIND -1))
#  $* is left over
if [ -n "$overwrite" ] ; then
  sudo mount -o remount,rw /
  sleep 2
  cd $GITHOME
  git pull origin master
  sleep 2
  sudo make install
  sleep 1
  sudo $PREFIX/swstopstart restart
  exit 0
fi
